### ISSUE TITLE
BZOJ 2654: tree | SW_Wind's blog

### ISSUE THREAD

**Issue by swwind** [swwind/swwind.github.io#74]
https://swwind.github.io/2017/06/02/BZOJ-2654-tree/

**Comment by j324h9** [comment]
似乎有问题？试一下这组数据
4 4 2
1 2 5 0
2 3 6 0
3 4 7 0
1 3 8 1
答案应该是20（选(1,2)(3,4)(1,3)边）

**Comment by swwind** [comment]
看起来这题错误的贪心也能过。。
@j324h9 感谢指正，我试着改一下
